import { chromium, expect } from '@playwright/test';
console.log('Launching browser');
const browser=await chromium.launch({headless:true,timeout:25000});
try {
const page=await browser.newPage({viewport:{width:1440,height:960}});
const errors:string[]=[];
const base=process.env.LUMEN_TEST_URL??'http://127.0.0.1:8080';
const large=process.env.LUMEN_TEST_LARGE==='1';
page.on('pageerror',error=>errors.push(error.message));
page.on('console',msg=>{if(msg.type()==='error')console.log('console:',msg.text().slice(0,300));});
console.log('Opening app');
await page.goto(base,{timeout:25000,waitUntil:'domcontentloaded'});
await page.waitForTimeout(6000);
await page.locator('flt-semantics-placeholder').evaluateAll(elements=>elements.forEach(e=>(e as HTMLElement).click()));
await page.waitForTimeout(1000);
await page.screenshot({path:'.tools/screenshots/setup.png',fullPage:true});
console.log((await page.locator('body').innerText()).slice(0,4000));
console.log('inputs',await page.locator('input').evaluateAll(es=>es.map(e=>({label:e.getAttribute('aria-label'),type:e.type,placeholder:e.placeholder}))));
async function enter(label:string,value:string){
  const field=page.locator(`input[aria-label="${label}"],textarea[aria-label="${label}"]`);
  await field.click({force:true});await page.waitForTimeout(200);
  await page.keyboard.press('Control+A');await page.keyboard.type(value);
}
await enter('Administrator name','Alex');
await enter('Password','test password 2026');
await page.getByRole('button',{name:'Create your space →',exact:true}).click();
await expect(page.getByText('YOUR SPACE',{exact:true})).toBeVisible({timeout:20000});
await page.screenshot({path:'.tools/screenshots/home-empty.png'});
await page.getByRole('button',{name:'Add a playlist',exact:true}).click();
await enter('Playlist name','Test library');
await enter('Playlist URL',base+(large?'/fixtures/large.m3u?count=10000':'/fixtures/playlist.m3u'));
await enter('XMLTV EPG URL (optional)',base+'/fixtures/epg.xml');
await enter('Playlist refresh','5');
await enter('EPG refresh','7');
await page.getByRole('button',{name:'Test connection',exact:true}).click();
await expect(page.getByText(/Playlist is reachable/)).toBeVisible({timeout:20000});
const started=Date.now();
await page.getByRole('button',{name:'Add playlist',exact:true}).click();
await expect(page.locator('[aria-label*="World News"]').first()).toBeVisible({timeout:120000});
console.log(`Import completed in ${Date.now()-started}ms (${large?'10000':'2'} channels)`);
await page.screenshot({path:'.tools/screenshots/home.png'});
await page.getByText('TV guide',{exact:true}).click();
await expect(page.getByRole('button',{name:/^The world this evening/})).toBeVisible({timeout:15000});
const storageBefore=await page.evaluate(async()=>await navigator.storage.estimate());
await page.waitForTimeout(6000);
const storageAfter=await page.evaluate(async()=>await navigator.storage.estimate());
console.log('Storage after guide settled:',JSON.stringify({before:storageBefore.usage,after:storageAfter.usage}));
await page.screenshot({path:'.tools/screenshots/guide.png'});
await page.getByText('Settings',{exact:true}).click();
await expect(page.locator('[aria-label*="refresh every 5h · EPG every 7h"]').first()).toBeVisible();
await page.getByRole('button',{name:'Edit playlist',exact:true}).focus();
await page.keyboard.press('Enter');
await expect(page.getByText('Playlist settings',{exact:true})).toBeVisible();
await page.screenshot({path:'.tools/screenshots/playlist-settings.png'});
await page.getByRole('button',{name:'Cancel',exact:true}).click();
await page.getByRole('button',{name:'Add profile',exact:true}).focus();
await page.keyboard.press('Enter');
await enter('Profile name','Viewer');
await enter('PIN','0042');
await page.getByRole('button',{name:'Create profile',exact:true}).click();
await expect(page.getByRole('group',{name:/Viewer Personal profile/})).toBeVisible({timeout:20000});
await page.getByRole('button',{name:'Add profile',exact:true}).focus();
await page.keyboard.press('Enter');
await enter('Profile name','Hidden');
await enter('PIN','0099');
await page.getByRole('button',{name:'Create profile',exact:true}).click();
const hidden=page.getByRole('group',{name:/Hidden Personal profile/});
await expect(hidden).toBeVisible({timeout:20000});
await hidden.getByRole('button',{name:'Hide from sign-in list',exact:true}).focus();
await page.keyboard.press('Enter');
await expect(hidden.getByRole('button',{name:'Show in sign-in list',exact:true})).toBeVisible();
await page.reload();
await page.locator('flt-semantics-placeholder').waitFor({state:'attached',timeout:30000});
await page.locator('flt-semantics-placeholder').evaluateAll(elements=>elements.forEach(e=>(e as HTMLElement).click()));
await expect(page.getByText('Who’s watching?',{exact:true})).toBeVisible({timeout:15000});
await expect(page.locator('body')).not.toContainText('Hidden');
await expect(page.locator('body')).not.toContainText('Alex');
await enter('PIN','0042');
await page.getByRole('button',{name:'Start watching →',exact:true}).click();
await expect(page.getByText('YOUR SPACE',{exact:true})).toBeVisible({timeout:20000});
await page.reload();
await page.locator('flt-semantics-placeholder').waitFor({state:'attached',timeout:30000});
await page.locator('flt-semantics-placeholder').evaluateAll(elements=>elements.forEach(e=>(e as HTMLElement).click()));
await expect(page.getByText('Who’s watching?',{exact:true})).toBeVisible({timeout:15000});
await page.getByRole('button',{name:'Sign in by account name',exact:true}).click();
await enter('Account name','Hidden');
await enter('PIN or password','0099');
await page.getByRole('button',{name:'Start watching →',exact:true}).click();
await expect(page.getByText('YOUR SPACE',{exact:true})).toBeVisible({timeout:20000});
await page.reload();
await page.locator('flt-semantics-placeholder').waitFor({state:'attached',timeout:30000});
await page.locator('flt-semantics-placeholder').evaluateAll(elements=>elements.forEach(e=>(e as HTMLElement).click()));
await page.getByRole('button',{name:'Administrator sign-in',exact:true}).click();
await enter('Password','test password 2026');
await page.getByRole('button',{name:'Start watching →',exact:true}).click();
await expect(page.getByText('YOUR SPACE',{exact:true})).toBeVisible({timeout:20000});
await page.reload();
await page.locator('flt-semantics-placeholder').waitFor({state:'attached',timeout:30000});
await page.locator('flt-semantics-placeholder').evaluateAll(elements=>elements.forEach(e=>(e as HTMLElement).click()));
await page.setViewportSize({width:390,height:844});
await page.waitForTimeout(500);
await expect(page.getByText('Who’s watching?',{exact:true})).toBeVisible();
await page.screenshot({path:'.tools/screenshots/mobile-login.png'});
console.log('PASS: admin setup, playlist import, EPG, custom intervals, PIN user creation/sign-in, and persistence');
console.log('errors',errors);
if(errors.length)process.exitCode=1;
} finally {
  await browser.close();
}
