import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:960}});
const errors:string[]=[];
const requests:string[]=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('request',r=>requests.push(r.url()));
const base='http://127.0.0.1:8082';
async function enter(label:string,value:string){
  await page.locator(`input[aria-label="${label}"],textarea[aria-label="${label}"]`).click({force:true});
  await page.waitForTimeout(200);await page.keyboard.press('Control+A');await page.keyboard.type(value);
}
async function activate(name:string|RegExp){await page.getByRole('button',{name,exact:typeof name==='string'}).first().focus();await page.keyboard.press('Enter');}
try {
  await page.route('**/fixtures/xtream/player_api.php*', async route => {
    const response = await route.fetch();
    if (new URL(route.request().url()).searchParams.get('action') === 'get_series') {
      const data = await response.json();
      data.forEach((series:any) => series.cover = base + '/icons/Icon-192.png');
      await route.fulfill({json:data});
    } else await route.fulfill({response});
  });
  let guideBody:string|undefined;
  await page.route('**/fixtures/xtream/xmltv.php*',async route=>{
    if(guideBody===undefined)guideBody=await (await route.fetch()).text();
    await route.fulfill({status:200,contentType:'application/xml',body:guideBody});
  });
  const started=Date.now();
  await page.goto(base);
  await page.locator('flt-semantics-placeholder').waitFor({state:'attached',timeout:30000});
  await page.locator('flt-semantics-placeholder').evaluateAll(es=>es.forEach(e=>(e as HTMLElement).click()));
  await page.locator('input[aria-label="Administrator name"]').waitFor();
  console.log(`Cold startup to sign-in: ${Date.now()-started}ms`);
  await enter('Administrator name','Tester');await enter('Password','test password 2026');
  await activate('Create your space →');
  await activate('Add a playlist');
  await activate(/^Playlist type/);
  await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');
  await enter('Playlist name','Feature fixture');await enter('Server URL',base+'/fixtures/xtream');
  await enter('Username','demo');await enter('Password','secret');
  await activate('Add playlist');
  await expect(page.locator('[aria-label*="World News"]').first()).toBeVisible({timeout:30000});
  await page.waitForTimeout(1000);
  await activate('Refresh playlists and guide');
  await expect(page.locator('body')).toContainText('library: 0 added · 0 changed · 0 removed · 4 unchanged',{timeout:30000});
  await expect(page.locator('body')).toContainText('guide: 0 added · 0 changed · 0 removed · 1 unchanged',{timeout:30000});
  await expect(page.locator('body')).not.toContainText('refresh failed');
  await activate('Live TV');
  await activate('Favorite category Sport');
  await expect(page.getByRole('button',{name:'Unfavorite category Sport',exact:true})).toBeVisible();
  await activate('For you');
  await activate('Live TV');
  await expect(page.getByRole('button',{name:'Unfavorite category Sport',exact:true})).toBeVisible();
  await expect(page.getByText('Categories',{exact:true})).toBeVisible();
  await expect(page.locator('body')).not.toContainText('Cinema');
  await enter('Filter categories','nEw');
  await expect(page.getByRole('button',{name:'News',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Sport',exact:true})).toHaveCount(0);
  await enter('Filter categories','does-not-exist');
  await expect(page.getByText('No matching categories.',{exact:true})).toBeVisible();
  await activate('Clear category filter');
  await expect(page.getByRole('button',{name:'Sport',exact:true})).toBeVisible();
  await activate('News');
  await expect(page.getByRole('button',{name:/World News/})).toBeVisible();
  await expect(page.locator('body')).not.toContainText('Match Day');
  await enter('Filter channels','Match');
  await expect(page.getByText('No matching channels.',{exact:true})).toBeVisible();
  await activate('Clear channel filter');
  await expect(page.getByRole('button',{name:/World News/})).toBeVisible();
  await page.screenshot({path:'.tools/screenshots/category-guide.png'});
  await activate(/World News/);
  const video=page.locator('video');
  await expect(video).toHaveCount(1,{timeout:20000});
  await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.currentTime),{timeout:25000}).toBeGreaterThan(1);
  expect(await page.evaluate(()=>document.fullscreenElement===null)).toBe(true);
  await page.mouse.click(700,400);
  await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.paused)).toBe(true);
  await page.mouse.click(700,400);
  await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.paused)).toBe(false);
  await page.mouse.move(800,700);
  await activate('Audio and subtitles');
  await expect(page.getByText('Sound & subtitles',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Norwegian',exact:true}).click({force:true});
  await expect.poll(()=>requests.some(url=>url.includes('norwegian-'))).toBe(true);
  await page.getByRole('tab',{name:'Subtitles',exact:true}).click();
  await page.waitForTimeout(600);
  await page.getByRole('button',{name:'English captions',exact:true}).click({force:true});
  await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>Array.from(v.textTracks).some(t=>t.mode==='showing' && (t.activeCues?.length??0)>0)),{timeout:15000}).toBe(true);
  await page.screenshot({path:'.tools/screenshots/track-picker.png'});
  await video.evaluate((v:HTMLVideoElement) => {
    const track = v.addTextTrack('captions','Browser captions','en');
    track.addCue(new VTTCue(0,90,'Browser caption test'));
    track.mode='hidden';
  });
  await expect(page.getByRole('button',{name:'Browser captions',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Browser captions',exact:true}).click({force:true});
  await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>Array.from(v.textTracks).some(t=>t.label==='Browser captions' && t.mode==='showing'))).toBe(true);
  await activate('Done');
  await page.mouse.move(800,500);await page.waitForTimeout(500);
  await page.screenshot({path:'.tools/screenshots/player-overlay.png'});
  await activate('Close player');
  await activate('Series');
  await enter('Find a channel, film, or series','Cinema Only');
  await expect(page.getByText('Search series',{exact:true})).toBeVisible();
  await expect(page.getByText('Nothing here yet.',{exact:true})).toBeVisible();
  await activate('Movies');await enter('Find a channel, film, or series','Cinema Only');
  await expect(page.getByText('Search movies',{exact:true})).toBeVisible();
  await expect(page.getByRole('group',{name:/Cinema Only/})).toBeVisible();
  await activate('Series');await page.getByRole('group',{name:/Drama Only/}).click({force:true});
  await expect(page.getByRole('button',{name:/Season 2 · 2 episodes/})).toBeVisible({timeout:20000});
  await expect(page.locator('body')).not.toContainText('Episode 3');
  await activate(/Season 2 · 2 episodes/);
  await page.waitForTimeout(600);
  await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');
  await expect(page.getByRole('button',{name:/Episode 3/})).toBeVisible();
  await page.screenshot({path:'.tools/screenshots/season-picker.png'});
  await expect(page.getByRole('img',{name:'Drama Only artwork'})).toBeVisible();
  await activate(/Episode 3/);
  await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.currentTime),{timeout:25000}).toBeGreaterThan(1);
  await expect(page.getByRole('progressbar')).toHaveCount(0);
  await page.waitForTimeout(600);
  expect(await page.evaluate(()=>document.fullscreenElement===null)).toBe(true);
  await page.mouse.move(800,700);
  await page.mouse.click(700,400);
  await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.paused)).toBe(true);
  await page.keyboard.press('5');
  await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>Math.abs(v.currentTime-v.duration*.5))).toBeLessThan(1);
  await page.keyboard.press('ArrowLeft');
  await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>Math.abs(v.currentTime-(v.duration*.5-10)))).toBeLessThan(1);
  await activate('Forward 10 seconds');
  await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>Math.abs(v.currentTime-v.duration*.5))).toBeLessThan(1);
  await page.mouse.click(700,400);
  await activate('Episodes');
  await expect(page.getByRole('button',{name:/Episode 3 Now playing/})).toBeVisible();
  await activate(/^Season Season 10$/);
  await page.waitForTimeout(600);
  await page.keyboard.press('ArrowUp');await page.keyboard.press('Enter');
  await page.waitForTimeout(600);
  await activate(/Episode 1/);
  await expect(page.getByRole('alertdialog')).toHaveCount(0);
  await expect.poll(()=>video.evaluate((v:HTMLVideoElement)=>v.currentTime),{timeout:25000}).toBeGreaterThan(1);
  await page.mouse.move(700,600);
  expect(requests.some(url=>url.includes('/series/demo/secret/21.m3u8'))).toBe(true);
  await activate('Episodes');
  await expect(page.getByRole('button',{name:/Episode 1 Now playing/})).toBeVisible();
  await page.screenshot({path:'.tools/screenshots/in-player-episode.png'});
  await activate('Close');
  await page.mouse.move(750,600);
  await activate('Close player');
  await activate('Back');
  await activate('For you');
  await enter('Find a channel, film, or series','Episode 1');
  await expect(page.getByText('Nothing here yet.',{exact:true})).toBeVisible();
  await expect(page.getByRole('checkbox',{name:'Show episodes',exact:true})).not.toBeChecked();
  await page.getByRole('checkbox',{name:'Show episodes',exact:true}).click({force:true});
  await expect(page.getByRole('group',{name:/Episode 1/}).first()).toBeVisible();
  expect(errors).toEqual([]);
  console.log('PASS: category guide scoping, real HLS playback, alternate audio fetch, rendered subtitles, overlay controls, scoped search, numeric seasons');
} catch(e) {
  console.log((await page.locator('body').innerText()).slice(-6000));
  console.log(await page.locator('body').ariaSnapshot());
  console.log('Video diagnostics',await page.locator('video').evaluateAll(videos=>videos.map((v:HTMLVideoElement)=>({time:v.currentTime,paused:v.paused,ready:v.readyState,tracks:Array.from(v.textTracks).map(t=>({label:t.label,mode:t.mode,cues:t.cues?.length,active:t.activeCues?.length}))}))));
  console.log('Subtitle requests',requests.filter(u=>u.includes('subtitles')||u.includes('.vtt')));
  await page.screenshot({path:'.tools/screenshots/features-failure.png'});
  throw e;
} finally {await browser.close();}
